<?php

declare(strict_types=1);

namespace Sopheak\Core\Utilities;

use Sopheak\Core\Services\RecordConfigService;
use Sopheak\Core\Types\RecordTableType;

class DefaultValidationUtils
{
    public static function buildCreateRules(RecordTableType $tableSchema): array
    {
        return self::buildRules($tableSchema, 'create');
    }

    public static function buildUpdateRules(RecordTableType $tableSchema, mixed $id): array
    {
        return self::buildRules($tableSchema, 'update', $id);
    }

    private static function buildRules(RecordTableType $tableSchema, string $operation, mixed $id = null): array
    {
        $columns = $tableSchema->columns ?? [];
        if ([] === $columns) {
            return [];
        }

        $actualTableName = $tableSchema->table ?? '';
        $primaryKey = $tableSchema->primaryKey ?? 'id';
        $writeDisabled = array_flip($tableSchema->columnWriteDisabled ?? []);
        $systemColumns = array_filter([
            $primaryKey,
            'created_at',
            'updated_at',
            'deleted_at',
        ]);

        $uniqueColumns = RecordConfigService::defaultValidationIncludeUnique() && $actualTableName !== ''
            ? SchemaRegistryUtils::getUniqueColumns($actualTableName)
            : [];

        $foreignKeys = RecordConfigService::defaultValidationIncludeForeignKeys() && $actualTableName !== ''
            ? SchemaRegistryUtils::getForeignKeys($actualTableName)
            : [];

        $rules = [];

        foreach ($columns as $column => $info) {
            if (!is_string($column)) {
                continue;
            }

            if ('' === $column) {
                continue;
            }

            if (isset($writeDisabled[$column])) {
                continue;
            }

            if (in_array($column, $systemColumns, true)) {
                continue;
            }

            if ($tableSchema->hasTenantId && $column === RecordConfigService::tenantColumn()) {
                continue;
            }

            $columnRules = [];

            $nullable = (bool) ($info['nullable'] ?? true);

            if (RecordConfigService::defaultValidationIncludeRequired()) {
                $isRequired = self::isRequiredColumn($info);
                if ('update' === $operation) {
                    $columnRules[] = 'sometimes';
                    if ($isRequired) {
                        $columnRules[] = 'required';
                    }
                } else {
                    $columnRules[] = $isRequired ? 'required' : 'nullable';
                }
            } elseif ('update' === $operation) {
                $columnRules[] = 'sometimes';
            }

            if ('update' === $operation && $nullable) {
                $columnRules[] = 'nullable';
            }

            if (RecordConfigService::defaultValidationIncludeTypes()) {
                $typeRule = self::mapTypeToRule((string) ($info['type'] ?? ''), (string) ($info['udt_name'] ?? ''));
                if ($typeRule !== null) {
                    $columnRules[] = $typeRule;
                }
            }

            if (RecordConfigService::defaultValidationIncludeUnique() && in_array($column, $uniqueColumns, true)) {
                if ('update' === $operation && $id !== null) {
                    $columnRules[] = sprintf('unique:%s,%s,%s,%s', $actualTableName, $column, $id, $primaryKey);
                } else {
                    $columnRules[] = sprintf('unique:%s,%s', $actualTableName, $column);
                }
            }

            if (RecordConfigService::defaultValidationIncludeForeignKeys() && isset($foreignKeys[$column])) {
                $foreign = $foreignKeys[$column];
                $columnRules[] = sprintf('exists:%s,%s', $foreign['table'], $foreign['column']);
            }

            if ([] !== $columnRules) {
                $rules[$column] = implode('|', array_values(array_unique($columnRules)));
            }
        }

        return $rules;
    }

    /**
     * Whether a create must supply this column: not nullable, no default and
     * not generated by the database. Shared with the MCP payload schemas so
     * what an agent is told is required matches what validation enforces.
     *
     * @param array<string, mixed> $info
     */
    public static function isRequiredColumn(array $info): bool
    {
        $nullable = (bool) ($info['nullable'] ?? true);
        $hasDefault = array_key_exists('default', $info) && $info['default'] !== null;

        return !$nullable && !$hasDefault && !self::isAutoGenerated($info);
    }

    /**
     * @param array<string, mixed> $info
     */
    private static function isAutoGenerated(array $info): bool
    {
        $extra = strtolower((string) ($info['extra'] ?? ''));
        if (str_contains($extra, 'auto_increment')) {
            return true;
        }

        $default = strtolower((string) ($info['default'] ?? ''));
        if (str_contains($default, 'nextval(')) {
            return true;
        }

        $key = strtolower((string) ($info['key'] ?? ''));

        return $key === 'pri';
    }

    private static function mapTypeToRule(string $type, string $udtName): ?string
    {
        $rawType = strtolower($type !== '' ? $type : $udtName);
        $rawType = preg_replace('/\([^)]*\)/', '', $rawType);
        $rawType = str_replace('character varying', 'varchar', $rawType);
        $rawType = str_replace('character', 'char', $rawType);

        if (str_contains($rawType, 'uuid')) {
            return 'uuid';
        }

        if (in_array($rawType, ['int2', 'int4', 'int8', 'integer', 'bigint', 'smallint', 'serial', 'bigserial'], true)) {
            return 'integer';
        }

        if (in_array($rawType, ['numeric', 'decimal', 'float4', 'float8', 'real', 'double precision', 'double', 'float'], true)) {
            return 'numeric';
        }

        if (in_array($rawType, ['bool', 'boolean'], true)) {
            return 'boolean';
        }

        if (str_contains($rawType, 'json')) {
            return 'array';
        }

        if (str_contains($rawType, 'date') || str_contains($rawType, 'timestamp')) {
            return 'date';
        }

        if (str_contains($rawType, 'time')) {
            return 'string';
        }

        if (str_contains($rawType, 'char') || str_contains($rawType, 'text') || str_contains($rawType, 'varchar')) {
            return 'string';
        }

        return null;
    }
}
